GET http://localhost:3000/todos/?status=TO%20DO
####

GET http://localhost:3000/todos/?priority=HIGH
####

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
####

GET http://localhost:3000/todos/?search_q=Buy
####
GET http://localhost:3000/todos/?category=WORK&status=DONE
####

GET http://localhost:3000/todos/?category=HOME
###

GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH
####

GET http://localhost:3000/todos/2/
####

GET http://localhost:3000/todos/4/
####

GET http://localhost:3000/agenda/?date=2021-12-23/
####

POST http://localhost:3000/todos/
Content-Type: application/json

{
    "id": 6,
    "todo": "Finalize event theme",
    "priority": "LOW",
    "status": "TO DO",
    "category": "HOME",
    "due_date": "2021-03-23"
}
####
PUT http://localhost:3000/todos/2/
Content-Type: application/json

{
    "status": "DONE"
}
####
PUT http://localhost:3000/todos/3/
Content-Type: application/json

{
    "priority": "HIGH"
}
####

PUT http://localhost:3000/todos/5/
Content-Type: application/json

{
    "todo": "Clean the green"
}
####

PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
    "category": "LEARNING"
}
####

DELETE http://localhost:3000/todos/1/

####
